"""schedule block last reminded at

Revision ID: 06cd6874b8e2
Revises: 502114687fe5
Create Date: 2026-09-13 12:51:00.556885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06cd6874b8e2'
down_revision: Union[str, Sequence[str], None] = '502114687fe5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_blocks', sa.Column('last_reminded_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule_blocks', 'last_reminded_at')
    # ### end Alembic commands ###
