"""initial_schema

Revision ID: 46cb8a9d2b40
Revises: 
Create Date: 2026-08-02 12:17:50.372880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46cb8a9d2b40'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('telegram_chat_id', sa.String(length=64), nullable=True),
    sa.Column('telegram_username', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('onboarding_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_email', 'users', [sa.literal_column('lower(email)')], unique=True)
    op.create_index('idx_users_telegram_chat_id', 'users', ['telegram_chat_id'], unique=True, postgresql_where=sa.text('telegram_chat_id IS NOT NULL'))
    op.create_table('goals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('priority', sa.Enum('high', 'medium', 'low', name='priority_enum'), nullable=False),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('estimated_duration_minutes > 0', name='chk_goals_estimated_duration_minutes_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_goals_user_active', 'goals', ['user_id', 'is_active'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_token_id', sa.UUID(), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['replaced_by_token_id'], ['refresh_tokens.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('idx_refresh_tokens_hash', 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index('idx_refresh_tokens_user', 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('schedule_blocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Enum('mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun', name='day_of_week_enum'), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('is_flexible_block', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(is_flexible_block = true AND start_time IS NULL AND end_time IS NULL) OR (is_flexible_block = false AND start_time IS NOT NULL AND end_time IS NOT NULL AND end_time > start_time)', name='chk_fixed_block_has_times'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_schedule_blocks_user_day', 'schedule_blocks', ['user_id', 'day_of_week'], unique=False)
    op.create_table('telegram_link_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=12), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_telegram_link_codes_code', 'telegram_link_codes', ['code'], unique=True, postgresql_where=sa.text('consumed_at IS NULL'))
    op.create_table('reminders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('goal_id', sa.UUID(), nullable=True),
    sa.Column('label', sa.String(length=150), nullable=False),
    sa.Column('scheduled_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('pending', 'done', 'later', 'skipped', name='reminder_status_enum'), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('recurrence_rule', sa.Enum('none', 'daily', 'weekdays', name='recurrence_rule_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(is_recurring = false AND recurrence_rule = 'none') OR (is_recurring = true AND recurrence_rule != 'none')", name='chk_recurring_has_rule'),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reminders_goal', 'reminders', ['goal_id'], unique=False, postgresql_where=sa.text('goal_id IS NOT NULL'))
    op.create_index('idx_reminders_user_status', 'reminders', ['user_id', 'status'], unique=False)
    op.create_index('idx_reminders_user_time', 'reminders', ['user_id', 'scheduled_time'], unique=False)
    op.create_table('completion_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reminder_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('done', 'later', 'skipped', name='completion_action_enum'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reminder_id'], ['reminders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_completion_logs_reminder', 'completion_logs', ['reminder_id'], unique=False)
    op.create_index('idx_completion_logs_user_timestamp', 'completion_logs', ['user_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_completion_logs_user_timestamp', table_name='completion_logs')
    op.drop_index('idx_completion_logs_reminder', table_name='completion_logs')
    op.drop_table('completion_logs')
    op.drop_index('idx_reminders_user_time', table_name='reminders')
    op.drop_index('idx_reminders_user_status', table_name='reminders')
    op.drop_index('idx_reminders_goal', table_name='reminders', postgresql_where=sa.text('goal_id IS NOT NULL'))
    op.drop_table('reminders')
    op.drop_index('idx_telegram_link_codes_code', table_name='telegram_link_codes', postgresql_where=sa.text('consumed_at IS NULL'))
    op.drop_table('telegram_link_codes')
    op.drop_index('idx_schedule_blocks_user_day', table_name='schedule_blocks')
    op.drop_table('schedule_blocks')
    op.drop_index('idx_refresh_tokens_user', table_name='refresh_tokens')
    op.drop_index('idx_refresh_tokens_hash', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('idx_goals_user_active', table_name='goals')
    op.drop_table('goals')
    op.drop_index('idx_users_telegram_chat_id', table_name='users', postgresql_where=sa.text('telegram_chat_id IS NOT NULL'))
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
