"""schedule block reminder lead time

Revision ID: 502114687fe5
Revises: 2a3c46597641
Create Date: 2026-09-13 00:34:30.843139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '502114687fe5'
down_revision: Union[str, Sequence[str], None] = '2a3c46597641'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_blocks', sa.Column('remind_before_minutes', sa.Integer(), nullable=True))
    op.create_check_constraint('chk_reminder_lead_needs_a_start_time', 'schedule_blocks', 'remind_before_minutes IS NULL OR (is_flexible_block = false AND remind_before_minutes >= 0 AND remind_before_minutes <= 1440)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chk_reminder_lead_needs_a_start_time', 'schedule_blocks', type_='check')
    op.drop_column('schedule_blocks', 'remind_before_minutes')
    # ### end Alembic commands ###
